### ISSUE TITLE
Minecraft 1.20.1

### ISSUE THREAD

**Issue by ItzModzz** [Tanguygab/RealVillagerTowns#2]
Hello! I really love the work you are doing here with this plugin, but it doesn't work in minecraft 1.20.1, at least for me.

**Comment by Tanguygab** [comment]
oh right, I forgot I had this plugin lol
I'll do it tomorrow or this tomorrow

**Comment by ItzModzz** [comment]
Thank you, im really grateful if you make it work!

**Comment by Tanguygab** [comment]
Do you get any errors when you load the plugin? If yes, can you send them?

**Comment by ItzModzz** [comment]
Nope, when i load it i dont see any error, but it doesnt work anything and the villagers dont disguise when i try the /fixskin command it appears an error:
[10:32:22] [Server thread/INFO]: ItzModzz_ issued server command: /rvt fixskin aaa
[10:32:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'rvt' in plugin RealVillagerTowns v1.7.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1451) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.YamlConfiguration.getConfigurationSection(String)" is null
	at io.github.tanguygab.realvillagertowns.RealVillagerTowns.replaceSkin(RealVillagerTowns.java:583) ~[RealVillagerTowns-1.7.1.jar:?]
	at io.github.tanguygab.realvillagertowns.RVTCommand.process(RVTCommand.java:100) ~[RealVillagerTowns-1.7.1.jar:?]
	at io.github.tanguygab.realvillagertowns.RVTCommand.onCommand(RVTCommand.java:36) ~[RealVillagerTowns-1.7.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	
	Purpur is based on Paper if your plugin needs paper api, but i tried in a spigot only server and the problem is the same.

**Comment by ItzModzz** [comment]
When i do /rvt setvillager it disguises the villager to a skin and it appears the skin username, but no interaction menu or sometjing else

**Comment by Tanguygab** [comment]
this looks like a config issue, can you send your files?

**Comment by Tanguygab** [comment]
wait actually this isn't even the latest version I made, I think I fixed it already but didn't publish it xD I'll see later when I'm on my pc

**Comment by Tanguygab** [comment]
[RealVillagerTowns-2.0.0.zip](https://github.com/Tanguygab/RealVillagerTowns/files/13039418/RealVillagerTowns-2.0.0.zip)

**Comment by ItzModzz** [comment]
Hello, this versions works! But the villagers disguise like every 5 or 10 seconds and sometimes when they disguise they lose the skin and the aspect is like a normal villager

**Comment by Tanguygab** [comment]
yeah I had this issue too and still don't understand why, I'll have to check once again

**Comment by ItzModzz** [comment]
Hello, do you have any news?

**Comment by Tanguygab** [comment]
not really
